- name: Manage Users
  hosts: server_ip
  become: yes
  vars:
    users:
      - username: jacksparrow
        state: present
        password: "{{ 'BlackPearl' | password_hash('sha512') }}"
        groups: "sudo"
      - username: davyjones
        state: absent
  tasks:
    - name: Ensure users are present/absent
      user:
        name: "{{ item.username }}"
        state: "{{ item.state }}"
        password: "{{ item.password | default(omit) }}"
        groups: "{{ item.groups | default(omit) }}"
      loop: "{{ users }}"
  